# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget leptonica)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target leptonica
add_library(leptonica STATIC IMPORTED)

set_target_properties(leptonica PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/vcpkg/installed/x64-windows-static/include;C:/vcpkg/installed/x64-windows-static/include;C:/vcpkg/installed/x64-windows-static/include;C:/vcpkg/installed/x64-windows-static/include;C:/vcpkg/installed/x64-windows-static/include;C:/vcpkg/installed/x64-windows-static/include"
)

# Import target "leptonica" for configuration "Debug"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(leptonica PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "C:/vcpkg/installed/x64-windows-static/debug/lib/gif.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/jpegd.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/libpng16d.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/tiffd.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/lzmad.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/jpegd.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib;C:/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib"
  IMPORTED_LOCATION_DEBUG "C:/Liza_stuff/dhack/leptonica/vs16-x64/src/Debug/leptonica-1.80.0d.lib"
  )

# Import target "leptonica" for configuration "Release"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(leptonica PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "C:/vcpkg/installed/x64-windows-static/debug/lib/gif.lib;C:/vcpkg/installed/x64-windows-static/lib/jpeg.lib;C:/vcpkg/installed/x64-windows-static/lib/libpng16.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib;C:/vcpkg/installed/x64-windows-static/lib/tiff.lib;C:/vcpkg/installed/x64-windows-static/lib/lzma.lib;C:/vcpkg/installed/x64-windows-static/lib/jpeg.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib"
  IMPORTED_LOCATION_RELEASE "C:/Liza_stuff/dhack/leptonica/vs16-x64/src/Release/leptonica-1.80.0.lib"
  )

# Import target "leptonica" for configuration "MinSizeRel"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(leptonica PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "C:/vcpkg/installed/x64-windows-static/debug/lib/gif.lib;C:/vcpkg/installed/x64-windows-static/lib/jpeg.lib;C:/vcpkg/installed/x64-windows-static/lib/libpng16.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib;C:/vcpkg/installed/x64-windows-static/lib/tiff.lib;C:/vcpkg/installed/x64-windows-static/lib/lzma.lib;C:/vcpkg/installed/x64-windows-static/lib/jpeg.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Liza_stuff/dhack/leptonica/vs16-x64/src/MinSizeRel/leptonica-1.80.0.lib"
  )

# Import target "leptonica" for configuration "RelWithDebInfo"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(leptonica PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "C:/vcpkg/installed/x64-windows-static/debug/lib/gif.lib;C:/vcpkg/installed/x64-windows-static/lib/jpeg.lib;C:/vcpkg/installed/x64-windows-static/lib/libpng16.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib;C:/vcpkg/installed/x64-windows-static/lib/tiff.lib;C:/vcpkg/installed/x64-windows-static/lib/lzma.lib;C:/vcpkg/installed/x64-windows-static/lib/jpeg.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib;C:/vcpkg/installed/x64-windows-static/lib/zlib.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Liza_stuff/dhack/leptonica/vs16-x64/src/RelWithDebInfo/leptonica-1.80.0.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
